export enum SensorType {
  Accelerometer = 'accelerometer',
  Button = 'button',
  Buzzer = 'buzzer',
  Clock = 'clock',
  CloudStore = 'cloudstore',
  Gyroscope = 'gyroscope',
  Humidity = 'humidity',
  IrRecv = 'irrecv',
  IrTrans = 'irtrans',
  Led = 'led',
  LedDim = 'leddim',
  LedMatrix = 'ledmatrix',
  LedRgb = 'ledrgb',
  Light = 'light',
  Magnetometer = 'magnetometer',
  Motor = 'motor',
  Potentiometer = 'potentiometer',
  Range = 'range',
  Screen = 'screen',
  Servo = 'servo',
  Sound = 'sound',
  Stick = 'stick',
  Temperature = 'temperature',
  Wifi = 'wifi',
}
